config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships do
    put 'confirm', on: :member
  end
  resources :beer_clubs
  resources :users do
    post 'toggle_disabled', on: :member
  end

  get 'signup', to: 'users#new'

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'


  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  resources :ratings, only: [:index, :new, :create, :destroy]

  root 'breweries#index'

  resource :session, only: [:new, :create, :destroy]

  resources :places, only: [:index, :show]

  post 'places', to: 'places#search'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/brewery.rb
class Brewery < ApplicationRecord
  extend Top
  include RatingAverage

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 1040,
                                   less_than_or_equal_to: ->(_year) { Date.today.year },
                                   only_integer: true }
  # validates_numericality_of :year, less: ->(year) { 1040..Date.today.year }

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

  def print_report
    puts name
    puts "est. year #{year}"
    puts "# of beers #{beers.count}"
  end

  def restart
    self.year = 2018
    puts "changed to year #{year}"
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :ensure_that_admin, only: [:destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    expire

    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    expire

    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    expire

    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    expire

    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active ? "active" : "retired"

    redirect_to brewery, notice: "activity changed to #{new_status}"
  end

  def list
  end

  private

  def expire
    expire_fragment("brewerylist")
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end

  def authenticate
    admin_accounts = { "pekka" => "beer", "arto" => "foobar", "matti" => "ittam", "vilma" => "kangas" }

    authenticate_or_request_with_http_basic do |username, password|
      login_ok = if !username.empty? && !password.empty? && (password == admin_accounts[username])
                   true
                 else
                   false
                 end
      login_ok
    end
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_with(model: brewery, local: true) do |form| %>
  <% if brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery  %></td>
        <td><%= brewery.year %></td>
        <td><%= link_to('Edit', edit_brewery_path(brewery), class: 'btn btn-primary') if current_user %></td>
        <td><%= link_to('Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger') if current_user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<p>Number of active breweries: <%= @active_breweries.count %> </p>

<% cache "brewerylist", skip_digest: true do %>

  <%= render 'list', breweries: @active_breweries %>

  <p>Number of retired breweries: <%= @retired_breweries.count %> </p>

  <%= render 'list', breweries: @retired_breweries %>

<% end %>

<br>

<p>
  <%= link_to 'List of beers', beers_path %>
</p>

<p>
  <%= link_to 'New Brewery', new_brewery_path %>
</p>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" style="table table-hover">
  <tr>
    <th><a href="#" id="name">name</a></th>
    <th><a href="#" id="founded">founded</a></th>
    <th><a href="#" id="beercount"># of beers</a></th>
    <th><a href="#" id="active">active</a></th>
  </tr>
</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/panimot.html.erb
panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<% cache @brewery do %>

<h2>
  <%= @brewery.name %>
  <% if not @brewery.active %>
    <span class="badge badge-info">retired</span>
  <% end %>
</h2>

<p><i>Established in <%= @brewery.year %></i></p>

<p>
  <strong>Number of beers:</strong>
  <%= @brewery.beers.count %>
</p>

<p>
  <% @brewery.beers.each do |beer| %>
    <%= link_to beer.name, beer %>
  <% end %>
</p>

<p>
  <% if @brewery.ratings.empty? %>
    Has no ratings
  <% else %>
    Has <%= pluralize(@brewery.ratings.count, 'rating') %>, average <%= round(@brewery.average_rating) %>
  <% end %>
</p>

<% end %>

<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>

<% if current_user %>
  <%= link_to 'Edit', edit_brewery_path(@brewery), class: "btn btn-primary" if current_user %>
<% end %>

<%= link_to 'Back', breweries_path, class: "btn btn-primary" %>