config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships do
    put 'confirm', on: :member
  end
  resources :beer_clubs
  resources :users do
    post 'toggle_disabled', on: :member
  end

  get 'signup', to: 'users#new'

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'


  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  resources :ratings, only: [:index, :new, :create, :destroy]

  root 'breweries#index'

  resource :session, only: [:new, :create, :destroy]

  resources :places, only: [:index, :show]

  post 'places', to: 'places#search'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'breweries', breweries_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'beers', beers_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'beer clubs', beer_clubs_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ratings', ratings_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'places', places_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'users', users_path, class: 'nav-link' %>
          </li>
          <% if current_user %> <!-- user_path(id: current_user.id) -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user %>
                </a>
              <!-- <%= link_to(current_user, '#', class: 'nav-link dropdown toggle', role: 'button', data: { toggle: 'dropdown' } ) %> -->
              <div class="dropdown-menu">
                <%= link_to('new rating', new_rating_path, { class: 'dropdown-item' }) %>
                <%= link_to('join a club', new_membership_path, class: 'dropdown-item') %>
                <div class="dropdown-divider"></div>
                <%= link_to('sign out', signout_path, method: :delete, class: 'dropdown-item') %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'sign in', signin_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'sign up', signup_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <a href="/auth/github" class="nav-link"><span class="fa fa-github">&nbsp;</span>sign in with github</a>
            </li>
          <% end %> 
        </ul>
      </div>
    </nav>

    <div class="container">
      <% if notice %>
        <div class="alert alert-primary" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <div class="row">
        <div class="col-sm-8">
          <%= yield %>
        </div>
        <div class="col-sm-4">
          <img 
            src="http://www.cs.helsinki.fi/u/mluukkai/wadror/pint.jpg" 
            width="200"
            style="padding-top:30px"
          >
        </div>
      </div>
    </div>

    <% if current_user %>
      <p><%= current_user.username %> signed in</p>
    <% end %>  
  </body>
</html>